globus:
  globus_endpoints:

    # 7.0.1.2 ENDPOINTS

    nersc7012:
      root_path: /global/cfs/cdirs/als/gsharing/data_mover/7012
      uri: nersc.gov
      uuid: d40248e6-d874-4f7b-badd-2c06c16f1a58
      name: nersc7012

    data7012:
      root_path: /
      uri: hpc.lbl.gov
      uuid: 741b96e1-1b98-42a8-918d-daacc24c145f
      name: data7012

    # 7.3.3 ENDPOINTS

    bl733-nersc-alsdev:
      root_path: /global/cfs/cdirs/als/data_mover/7.3.3/
      uri: nersc.gov
      uuid: d40248e6-d874-4f7b-badd-2c06c16f1a58
      name: bl733-nersc-alsdev

    bl733-nersc-alsdev_raw:
      root_path: /global/cfs/cdirs/als/data_mover/7.3.3/raw
      uri: nersc.gov
      uuid: d40248e6-d874-4f7b-badd-2c06c16f1a58
      name: bl733-nersc-alsdev_raw

    bl733-als-data733:
      root_path: /
      uri: data733.lbl.gov
      uuid: 26b3d2cf-fd80-4a64-a78f-38a155aca926
      name: bl733-als-data733

    bl733-als-data733_raw:
      root_path: /
      uri: data733.lbl.gov
      uuid: 26b3d2cf-fd80-4a64-a78f-38a155aca926
      name: data733_raw

    bl733-beegfs-data:
      root_path: /beamline_staging/bl733/raw/
      uri: beegfs.als.lbl.gov
      uuid: d33b5d6e-1603-414e-93cb-bcb732b7914a
      name: bl733-beegfs-data

    # 8.3.2 ENDPOINTS

    spot832:
      root_path: /
      uri: spot832.lbl.gov
      uuid: 44ae904c-ab64-4145-a8f0-7287de38324d
      name: spot832

    data832:
      root_path: /data
      uri: data832.lbl.gov
      uuid: 75b478b2-37af-46df-bfbd-71ed692c6506
      name: data832

    data832_raw:
      root_path: /data/raw
      uri: data832.lbl.gov
      uuid: 75b478b2-37af-46df-bfbd-71ed692c6506
      name: data832_raw

    data832_scratch:
      root_path: /data/scratch/globus_share
      uri: data832.lbl.gov
      uuid: 75b478b2-37af-46df-bfbd-71ed692c6506
      name: data832_scratch

    alcf832_synaps_raw:
      root_path: /data/bl832/raw
      uri: alcf.anl.gov
      uuid: TBD
      name: alcf832_synaps_raw

    alcf832_synaps_recon:
      root_path: /data/bl832/scratch/reconstruction/
      uri: alcf.anl.gov
      uuid: TBD
      name: alcf832_synaps_recon

    alcf832_synaps_segment:
      root_path: /data/bl832/scratch/segmentation/
      uri: alcf.anl.gov
      uuid: TBD
      name: alcf832_synaps_segment

    alcf832_iri_raw:
      root_path: /data/raw
      uri: alcf.anl.gov
      uuid: 55c3adf6-31f1-4647-9a38-52591642f7e7
      name: alcf_iri_raw

    alcf832_iri_scratch:
      root_path: /data/scratch
      uri: alcf.anl.gov
      uuid: 55c3adf6-31f1-4647-9a38-52591642f7e7
      name: alcf_iri_scratch

    alcf_eagle832:
      root_path: /IRIBeta/als/example
      uri: alcf.anl.gov
      uuid: 05d2c76a-e867-4f67-aa57-76edeb0beda0
      name: alcf_eagle832

    alcf_home832:
      root_path: / #alcf /home/username
      uri: alcf.anl.gov
      uuid: 9032dd3a-e841-4687-a163-2720da731b5b
      name: alcf_home832

    nersc_alsdev:
      root_path: /global/homes/a/alsdev/test_directory/
      uri: nersc.gov
      uuid: d40248e6-d874-4f7b-badd-2c06c16f1a58
      name: nersc_alsdev

    nersc832_alsdev_raw:
      root_path: /global/cfs/cdirs/als/data_mover/8.3.2/raw
      uri: nersc.gov
      uuid: d40248e6-d874-4f7b-badd-2c06c16f1a58
      name: nersc832_alsdev_raw

    nersc832_alsdev_scratch:
      root_path: /global/cfs/cdirs/als/data_mover/8.3.2/scratch
      uri: nersc.gov
      uuid: d40248e6-d874-4f7b-badd-2c06c16f1a58
      name: nersc832_alsdev_scratch

    nersc832_alsdev_pscratch_raw:
      root_path: /pscratch/sd/a/alsdev/8.3.2/raw
      uri: nersc.gov
      uuid: d40248e6-d874-4f7b-badd-2c06c16f1a58
      name: nersc832_alsdev_pscratch_raw

    nersc832_alsdev_pscratch_scratch:
      root_path: /pscratch/sd/a/alsdev/8.3.2/scratch
      uri: nersc.gov
      uuid: d40248e6-d874-4f7b-badd-2c06c16f1a58
      name: nersc832_alsdev_pscratch_scratch

    nersc832_alsdev_recon_scripts:
      root_path: /global/cfs/cdirs/als/data_mover/8.3.2/tomography_reconstruction_scripts
      uri: nersc.gov
      uuid: d40248e6-d874-4f7b-badd-2c06c16f1a58
      name: nersc832_alsdev_recon_scripts

    nersc832:
      root_path: /global/cfs/cdirs/als/data_mover/8.3.2
      uri: nersc.gov
      uuid: df82346e-9a15-11ea-b3c4-0ae144191ee3
      name: nersc832

    bl832-beegfs-raw:
      root_path: /global/beegfs/beamlines/bl832/raw/
      uri: beegfs.als.lbl.gov
      uuid: d33b5d6e-1603-414e-93cb-bcb732b7914a
      name: bl832-beegfs-raw

    bl832-beegfs-scratch:
      root_path: /global/beegfs/beamlines/bl832/scratch/
      uri: beegfs.als.lbl.gov
      uuid: d33b5d6e-1603-414e-93cb-bcb732b7914a
      name: bl832-beegfs-scratch

  globus_apps:
    als_transfer:
      client_id: ${GLOBUS_CLIENT_ID}
      client_secret: ${GLOBUS_CLIENT_SECRET}

harbor_images832:
  recon_image: tomorecon_nersc_mpi_hdf5@sha256:cc098a2cfb6b1632ea872a202c66cb7566908da066fd8f8c123b92fa95c2a43c
  multires_image: tomorecon_nersc_mpi_hdf5@sha256:cc098a2cfb6b1632ea872a202c66cb7566908da066fd8f8c123b92fa95c2a43c

ghcr_images832:
  recon_image: ghcr.io/als-computing/microct@sha256:1fdfb786726ee03301d624319e3d16702045072f38e2b0cca9d6237e5ab3f5ff
  multires_image: ghcr.io/als-computing/microct@sha256:1fdfb786726ee03301d624319e3d16702045072f38e2b0cca9d6237e5ab3f5ff

prefect:
  deployments:
  - type_spec: new_file_832
    uuid: ccf2cb27-d4f8-420b-8115-a5036c69b1da

scicat:
  jobs_api_url: https://dataportal.als.lbl.gov/api/ingest/jobs

mlflow:
  local:
    tracking_uri: http://localhost:5001
    registry_uri: http://localhost:5001
  dev:
    tracking_uri: http://mlflow-dev.computing.als.lbl.gov
    registry_uri: http://mlflow-dev.computing.als.lbl.gov
  prod:
    tracking_uri: https://mlflow.computing.als.lbl.gov
    registry_uri: https://mlflow.computing.als.lbl.gov
  staging:
    tracking_uri: https://mlflow-staging.computing.als.lbl.gov
    registry_uri: https://mlflow-staging.computing.als.lbl.gov
  amsc:
    tracking_uri: https://mlflow.american-science-cloud.org/
    registry_uri: https://mlflow.american-science-cloud.org/
    experiment_name: als-bl832-models

nersc_resources:
  iri:
    api_base_url: https://api.iri.nersc.gov
    compute_resource: "compute"
    # Perlmutter compute
    perlmutter_compute: "94351904-6dba-4c16-b5cd-fbd280d8615b"
    perlmutter_login: "e525a224-61c1-419f-9642-91168c792e39"
    perlmutter_realtime: "3776417d-747c-4753-895a-6323c17b9c98"
    perlmutter_job_submit: "3cf3c048-855e-4dd8-a189-065a483954bb"
    # Storage
    scratch: "43d8f6c0-f900-48ce-b267-73714103f4ac"
    homes: "65b28619-c3b6-4942-8da1-044a3b3a2a9e"
    common: "7e07a611-f927-4a39-a44d-b1d6e307accd"
    cfs: "59e80c79-4dfd-4c53-9c07-7405685fcd37"
    archive: "f4916c65-9001-49c2-b0bf-6fe4276b564c"
    # Services
    globus: "0a207df3-4bec-45b8-9060-13505d269da9"
    dtns: "a762cbdc-af7a-4b2b-9463-67f0189dd2ae"
  sfapi:
    api_base_url: https://api.nersc.gov/api/v1.2

hpc_submission_settings832:
  # ── RECON + MULTIRES SETTINGS ───────────────────────────────────────────────
  nersc_reconstruction:
    # ── SLURM resource allocation ─────────────────────────────────────────────
    qos: realtime
    account: als
    reservation: ""
    num_nodes: 4
    cpus-per-task: 128
    walltime: "0:30:00"
  nersc_multiresolution:
    # ── SLURM resource allocation ─────────────────────────────────────────────
    qos: realtime
    account: als
    reservation: ""
    cpus-per-task: 128
    walltime: "0:15:00"

  # ── PETIOLE SEGMENTATION SETTINGS ───────────────────────────────────────────
  nersc_segmentation_sam3:
    # ── SLURM resource allocation ─────────────────────────────────────────────
    qos: realtime
    account: als
    constraint: gpu
    reservation: ""
    num_nodes: 4
    ntasks-per-node: 1
    gpus-per-node: 4
    cpus-per-task: 128
    walltime: "00:30:00"
    # ── Inference parameters ──────────────────────────────────────────────────
    script_name: "src/inference_v6.py"
    batch_size: 1
    patch_size: 400
    confidence:
    - 0.5
    overlap: 0.25
    prompts:
    - "Phloem Fibers"
    - "Hydrated Xylem vessels"
    - "Air-based Pith cells"
    - "Dehydrated Xylem vessels"
    # ── Paths ─────────────────────────────────────────────────────────────────
    cfs_path: /global/cfs/cdirs/als/data_mover/8.3.2
    conda_env_path: /global/cfs/cdirs/als/data_mover/8.3.2/envs/sam3-py311
    seg_scripts_dir: /global/cfs/cdirs/als/data_mover/8.3.2/tomography_segmentation_scripts/inference_latest/forge_feb_seg_model_demo/
    checkpoints_dir: /global/cfs/cdirs/als/data_mover/8.3.2/tomography_segmentation_scripts/sam3_finetune/sam3/
    bpe_path: /global/cfs/cdirs/als/data_mover/8.3.2/tomography_segmentation_scripts/sam3_finetune/sam3/bpe_simple_vocab_16e6.txt.gz
    original_checkpoint_path: /global/cfs/cdirs/als/data_mover/8.3.2/tomography_segmentation_scripts/sam3_finetune/sam3/sam3.pt
    finetuned_checkpoint_path: /global/cfs/cdirs/als/data_mover/8.3.2/tomography_segmentation_scripts/sam3_finetune/sam3/checkpoint_v6.pt
  nersc_segmentation_dinov3:
    # ── SLURM resource allocation ─────────────────────────────────────────────
    qos: realtime
    account: als
    constraint: gpu
    reservation: ""
    num_nodes: 4
    ntasks-per-node: 1
    nproc_per_node: 4
    gpus-per-node: 4
    cpus-per-task: 128
    walltime: "00:30:00"
    # ── Inference parameters ──────────────────────────────────────────────────
    script_name: "src.inference_dino_v1"
    batch_size: 4
    # ── Paths ─────────────────────────────────────────────────────────────────
    cfs_path: /global/cfs/cdirs/als/data_mover/8.3.2
    conda_env_path: /global/cfs/cdirs/als/data_mover/8.3.2/envs/dino_demo
    seg_scripts_dir: /global/cfs/cdirs/als/data_mover/8.3.2/tomography_segmentation_scripts/inference_v5_multiseg/forge_feb_seg_model_demo/
    dino_checkpoint_path: /global/cfs/cdirs/als/data_mover/8.3.2/tomography_segmentation_scripts/dino/best.ckpt
  nersc_combine_segmentations:
    # ── SLURM resource allocation ─────────────────────────────────────────────
    qos: realtime
    account: als
    constraint: cpu
    reservation: ""
    num_nodes: 4
    ntasks: 128
    cpus-per-task: 1
    walltime: "00:30:00"
    # ── Combination parameters ────────────────────────────────────────────────
    script_name: "src.combine_sam_dino_v3"
    dilate_px: 5
    # ── Paths ─────────────────────────────────────────────────────────────────
    cfs_path: /global/cfs/cdirs/als/data_mover/8.3.2
    conda_env_path: /global/cfs/cdirs/als/data_mover/8.3.2/envs/dino_demo
    seg_scripts_dir: /global/cfs/cdirs/als/data_mover/8.3.2/tomography_segmentation_scripts/inference_latest/forge_feb_seg_model_demo

  # ── MOON SEGMENTATION SETTINGS ───────────────────────────────────────────
  nersc_segmentation_dinov3_moon:
    # ── SLURM resource allocation ─────────────────────────────────────────────
    qos: realtime
    account: als
    constraint: gpu
    reservation: ""
    num_nodes: 4
    ntasks-per-node: 1
    nproc_per_node: 4
    gpus-per-node: 4
    cpus-per-task: 128
    walltime: "00:59:00"
    # ── Inference parameters ──────────────────────────────────────────────────
    script_name: "src.inference_dino_v2"
    project: "moon"
    batch_size: 4
    # ── Paths ─────────────────────────────────────────────────────────────────
    cfs_path: /global/cfs/cdirs/als/data_mover/8.3.2
    conda_env_path: /global/cfs/cdirs/als/data_mover/8.3.2/envs/dino_demo
    seg_scripts_dir: /global/cfs/cdirs/als/data_mover/8.3.2/tomography_segmentation_scripts/moon_seg/forge_feb_seg_model_demo/
    dino_checkpoint_path: /global/cfs/cdirs/als/data_mover/8.3.2/tomography_segmentation_scripts/dino/best_moon.ckpt
